"""Optimization models and solvers."""

from retarget.core.enums import (
    ConvergenceMode,
    GeometrySource,
    NominalFallback,
    NonPenetrationSource,
    QposVariableKind,
)
from retarget.optimization.problem import (
    ConstraintContribution,
    LinearConstraint,
    ObjectiveContribution,
    QuadraticProblem,
    SolverResult,
    TermContext,
)
from retarget.optimization.registry import SolverFactory, constraint_terms, objective_terms, solver_factories
from retarget.optimization.solvers import (
    CvxpyClarabelSolver,
    NumpyLeastSquaresSolver,
    create_solver,
    resolve_solver_backend_name,
)
from retarget.optimization.spec import (
    ConstraintConfig,
    ConstraintConfigUnion,
    DiagonalRegularizationObjectiveConfig,
    FootLockConstraintConfig,
    FootStickingConstraintConfig,
    JointLimitsConstraintConfig,
    LaplacianObjectiveConfig,
    LinkTrackingObjectiveConfig,
    NominalTrackingObjectiveConfig,
    NonPenetrationConstraintConfig,
    ObjectiveConfig,
    ObjectiveConfigUnion,
    OptimizationProfile,
    SelfCollisionConstraintConfig,
    SmoothnessObjectiveConfig,
    SolverSpec,
    TrustRegionConstraintConfig,
)
from retarget.optimization.terms import (
    DiagonalRegularizationObjective,
    FootLockConstraint,
    FootStickingConstraint,
    JointLimitConstraint,
    LaplacianObjective,
    LinkTrackingObjective,
    NominalTrackingObjective,
    NonPenetrationConstraint,
    SelfCollisionConstraint,
    SmoothnessObjective,
    TrustRegionConstraint,
)
from retarget.optimization.validation import validate_optimization_references
from retarget.optimization.variables import QposVariableSpec, ResolvedQposVariables

__all__ = [
    "ConstraintConfig",
    "ConstraintConfigUnion",
    "ConstraintContribution",
    "ConvergenceMode",
    "CvxpyClarabelSolver",
    "DiagonalRegularizationObjective",
    "DiagonalRegularizationObjectiveConfig",
    "FootLockConstraint",
    "FootLockConstraintConfig",
    "FootStickingConstraint",
    "FootStickingConstraintConfig",
    "GeometrySource",
    "JointLimitConstraint",
    "JointLimitsConstraintConfig",
    "LaplacianObjective",
    "LaplacianObjectiveConfig",
    "LinearConstraint",
    "LinkTrackingObjective",
    "LinkTrackingObjectiveConfig",
    "NominalFallback",
    "NominalTrackingObjective",
    "NominalTrackingObjectiveConfig",
    "NonPenetrationConstraint",
    "NonPenetrationConstraintConfig",
    "NonPenetrationSource",
    "NumpyLeastSquaresSolver",
    "ObjectiveConfig",
    "ObjectiveConfigUnion",
    "ObjectiveContribution",
    "OptimizationProfile",
    "QposVariableKind",
    "QposVariableSpec",
    "QuadraticProblem",
    "ResolvedQposVariables",
    "SelfCollisionConstraint",
    "SelfCollisionConstraintConfig",
    "SmoothnessObjective",
    "SmoothnessObjectiveConfig",
    "SolverFactory",
    "SolverResult",
    "SolverSpec",
    "TermContext",
    "TrustRegionConstraint",
    "TrustRegionConstraintConfig",
    "constraint_terms",
    "create_solver",
    "objective_terms",
    "resolve_solver_backend_name",
    "solver_factories",
    "validate_optimization_references",
]
